# Generated by Django 5.1.3 on 2026-01-21 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50)),
                ('hsl_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('base_color1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods_base1', to='careapp.color')),
                ('base_color2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods_base2', to='careapp.color')),
                ('base_color3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moods_base3', to='careapp.color')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('advice_id', models.AutoField(primary_key=True, serialize=False)),
                ('advice_text', models.TextField()),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.mood')),
            ],
        ),
        migrations.CreateModel(
            name='StartLog',
            fields=[
                ('startlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('intensity', models.IntegerField(default=50)),
                ('startlog_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careapp.advice')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedColor',
            fields=[
                ('suggested_color_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggested_color_hsl', models.CharField(max_length=30)),
                ('order_index', models.PositiveSmallIntegerField(default=1)),
                ('startlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.startlog')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='EndLog',
            fields=[
                ('endlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('endlog_note', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='endlog_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.mood')),
                ('startlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careapp.startlog')),
                ('selected_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careapp.suggestedcolor')),
            ],
        ),
    ]
