# Generated by Django 5.2.7 on 2026-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_alter_endlog_created_at_alter_startlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
